version: '3.8'

services:
  web:
    container_name: server
    build:
      context: .
      dockerfile: web/Dockerfile
    command: yarn dev # override the default 'CMD ["yarn", "start"]' in web/Dockerfile. This is for hot-reloading in dev mode
    ports:
      - '8000:8000'
    env_file:
      - ./web/.env
    environment:
      - MONGO_URI=mongodb://mongo:27017/vtmp-db # This will override the MONGO_URI loaded above
    depends_on:
      - mongo
    volumes:
      - ./web/src:/app/web/src # This is a bind mount. "./web/src" is relative to the directory where "docker compose up" is run

  web-client:
    container_name: client
    build:
      context: .
      dockerfile: web-client/Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - ./web-client/.env
    depends_on:
      - web

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
