services:
  web:
    container_name: server
    build:
      context: .
      dockerfile: web/Dockerfile
      args:
        - NODE_ENV=development
    command: yarn dev # override the default 'CMD ["yarn", "start"]' in web/Dockerfile. This is for hot-reloading in dev mode
    ports:
      - '8000:8000'
    env_file:
      - ./web/.env
    environment:
      - MONGO_URI=mongodb://mongo:27017/vtmp-db?replicaSet=rs0 # This will override MONGO_URI loaded from .env above
    depends_on:
      - mongo
    volumes:
      # This creates bind mount between local ./web/src and the container's /app/web/src
      # "./web/src" is relative to root (where the command "docker compose up" is run)
      - ./web/src:/app/web/src

  web-client:
    container_name: client
    build:
      context: .
      dockerfile: web-client/Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - ./web-client/.env
    environment:
      - VITE_API_URL=http://localhost:8000 # This will override VITE_API_URL loaded from .env above
    depends_on:
      - web

  mongo:
    container_name: mongo
    image: mongo:latest
    command: ['--replSet', 'rs0', '--bind_ip_all', '--port', '27017'] # Enable replica set, which is required to use transaction
    ports:
      - '27017:27017'
    healthcheck: # Use healthcheck to retry to intiate the replica set named rs0 (only single node)
      test: >
        mongosh --quiet --eval '
          try {
            rs.status().ok || rs.initiate({ _id: "rs0", members: [ { _id: 0, host: "mongo:27017" } ] });
          } catch(e) {
            rs.initiate({ _id: "rs0", members: [ { _id: 0, host: "mongo:27017" } ] });
          }
        '
      interval: 5s
      timeout: 10s
      start_period: 5s
      retries: 10
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb # Another named volume to persist mongo container config between runs

volumes:
  mongo_data:
  mongo_config:
