services:
  web:
    container_name: server
    build:
      context: .
      dockerfile: web/Dockerfile
      args:
        - NODE_ENV=development
    command: yarn dev # override the default 'CMD ["yarn", "start"]' in web/Dockerfile. This is for hot-reloading in dev mode
    ports:
      - '8000:8000'
    env_file:
      - ./web/.env
    environment:
      - MONGO_URI=mongodb://mongo:27017/vtmp-db # This will override MONGO_URI loaded from .env above
      - LINK_PROCESSING_ENDPOINT=http://link-processing-service:8080/2015-03-31/functions/function/invocations
    depends_on:
      - mongo
    volumes:
      # This creates bind mount between local ./web/src and the container's /app/web/src
      # "./web/src" is relative to root (where the command "docker compose up" is run)
      - ./web/src:/app/web/src

  link-processing-service:
    container_name: link-processor
    build:
      context: .
      dockerfile: link-processing-service/Dockerfile
      args:
        - NODE_ENV=development
    platform: linux/amd64
    ports:
      - '9000:8080'
    env_file:
      - ./link-processing-service/.env
    environment:
      - API_URL=http://web:8000
    depends_on:
      - web

  discord-service:
    container_name: discord
    build:
      context: .
      dockerfile: discord-service/Dockerfile
      args:
        - NODE_ENV=development
    command: yarn dev
    ports:
      - '4000:4000'
    env_file:
      - ./discord-service/.env
    environment:
      - API_URL=http://web:8000
    depends_on:
      - web
    volumes:
      - ./discord-service/src:/app/discord-service/src

  ngrok:
    container_name: ngrok
    image: ngrok/ngrok:latest
    env_file:
      - ./discord-service/.env
    command: http --domain=expert-evolving-bengal.ngrok-free.app discord-service:4000
    depends_on:
      - discord-service

  web-client:
    container_name: client
    build:
      context: .
      dockerfile: web-client/Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - ./web-client/.env
    environment:
      - VITE_API_URL=http://localhost:8000 # This will override VITE_API_URL loaded from .env above
    depends_on:
      - web

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
