services:
  web:
    container_name: server
    build:
      context: .
      dockerfile: web/Dockerfile
      args:
        - BUILD_ENV=development
    command: yarn dev # override the default 'CMD ["yarn", "start"]' in web/Dockerfile. This is for hot-reloading in dev mode
    ports:
      - '8000:8000'
    env_file:
      - ./web/.env
    environment:
      - LINK_PROCESSING_ENDPOINT=http://link-processing-service:8080/2015-03-31/functions/function/invocations
    volumes:
      # This creates bind mount between local ./web/src and the container's /app/web/src
      # "./web/src" is relative to root (where the command "docker compose up" is run)
      - ./web/src:/app/web/src

  link-processing-service:
    container_name: link-processor
    build:
      context: .
      dockerfile: link-processing-service/Dockerfile
      args:
        - BUILD_ENV=development
    platform: linux/amd64
    ports:
      - '9000:8080'
    env_file:
      - ./link-processing-service/.env
    environment:
      - API_URL=http://web:8000
    depends_on:
      - web

  discord-service:
    container_name: discord
    build:
      context: .
      dockerfile: discord-service/Dockerfile
      args:
        - BUILD_ENV=development
    command: yarn dev
    ports:
      - '4000:4000'
    env_file:
      - ./discord-service/.env
    environment:
      - API_URL=http://web:8000
    depends_on:
      - web
    volumes:
      - ./discord-service/src:/app/discord-service/src
    profiles:
      - discord

  ngrok:
    container_name: ngrok
    image: ngrok/ngrok:latest
    env_file:
      - ./discord-service/.env
    command: http --domain=expert-evolving-bengal.ngrok-free.app discord-service:4000
    depends_on:
      - discord-service
    profiles:
      - discord

  web-client:
    container_name: client
    build:
      context: .
      dockerfile: web-client/Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - ./web-client/.env
    environment:
      - VITE_API_URL=http://localhost:8000 # This will override VITE_API_URL loaded from .env above
    depends_on:
      - web

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - '27017:27017'
    # Enable replica set, which is required to use transaction
    # Run multiple commands in sequence.
    # - Start mongod in the background, wait for it to be ready
    # - Then run the replica set initiation with rs.initiate()
    command: >
      bash -c "
        mongod --replSet rs0 --bind_ip_all --port 27017 &
        until mongosh --eval \"db.adminCommand('ping')\"; do
          echo 'Waiting for MongoDB to start...'
          sleep 2
        done
        mongosh --eval \"
          try {
            rs.status().ok || rs.initiate({ _id: 'rs0', members: [ { _id: 0, host: 'mongo:27017' } ] });
          } catch(e) {
            rs.initiate({ _id: 'rs0', members: [ { _id: 0, host: 'mongo:27017' } ] });
          }
        \"
        wait
      "
    volumes:
      - mongo_data:/data/db
    profiles:
      - local_mongo

volumes:
  mongo_data:
