# fly.toml app configuration file generated for vtmp-web on 2025-07-08T19:36:37-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'vtmp-web-test'
primary_region = 'sea'

[build]
  dockerfile = '../web/Dockerfile'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
[env]
  MONGO_URI="mongodb+srv://test:test123@cluster0.rsfy21b.mongodb.net/"
  PORT="8000"
  JWT_SECRET="vtmp-secret"
  SERVICE_JWT_SECRET="vtmp-secret"
  SERVICE_NAME="backend"
  GMAIL_EMAIL="son.dmai@gmail.com"
  GMAIL_APP_PASSWORD="abc"
  VTMP_WEB_URL="abc"
  LAMBDA_URL=""
  NODE_ENV="PROD"